---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/etc/httpd: Z
    io.kubernetes.cri-o.TTY/httpd-doc: "false"
    io.podman.annotations.autoremove/httpd-doc: "TRUE"
    io.podman.annotations.cid-file/httpd-doc: /run/httpd.cid
    io.podman.annotations.init/httpd-doc: "TRUE"
    io.podman.annotations.privileged/httpd-doc: "FALSE"
    io.podman.annotations.publish-all/httpd-doc: "FALSE"
  labels:
    app: httpd-doc
  name: httpd-doc
spec:
  containers:
  - image: localhost/httpd:latest
    name: httpd
    ports:
    - containerPort: 80
      hostPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - CAP_CHOWN
        - CAP_DAC_OVERRIDE
        - CAP_FSETID
        - CAP_FOWNER
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_SETGID
        - CAP_SETUID
        - CAP_SETFCAP
        - CAP_SETPCAP
        - CAP_SYS_CHROOT
        - CAP_KILL
        - CAP_AUDIT_WRITE
      seLinuxOptions:
        type: 'spc_t'
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /usr/local/apache2/htdocs
      name: htdocs
    resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
  volumes:
  - hostPath:
      path: tmpfs
      type: DirectoryOrCreate
    name: tmpfs
  - hostPath:
      path: /etc/httpd/htdocs
      type: Directory
    name: htdocs
