apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/etc/ecal: Z
    io.kubernetes.cri-o.TTY/ecal-subscriber: "false"
    io.podman.annotations.autoremove/ecal-subscriber: "TRUE"
    io.podman.annotations.cid-file/ecal-subscriber: /run/ecal-subscriber.cid
    io.podman.annotations.init/ecal-subscriber: "TRUE"
    io.podman.annotations.privileged/ecal-subscriber: "FALSE"
    io.podman.annotations.publish-all/ecal-subscriber: "FALSE"
  labels:
    app: ecal-subscriber
  name: ecal-subscriber
spec:
  hostNetwork: true
  containers:
  - image: localhost/ecal-cpp-subscriber:latest
    name: app
    command:
      - /bin/bash
      - -c
      - '/opt/app/_build/hello_world_rec'
    securityContext:
      seLinuxOptions:
        type: 'spc_t'
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /etc/ecal
      name: ecal
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
  volumes:
  - hostPath:
      path: tmpfs
      type: DirectoryOrCreate
    name: tmpfs
  - hostPath:
      path: /etc/ecal
      type: Directory
    name: ecal
