apiVersion: v1/apps
kind: Deployment
metadata:
  name: ecal-sample-pubsub
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        bind-mount-options:/etc/ecal: Z
        io.kubernetes.cri-o.TTY/ecal-sample-pubsub: "false"
        io.podman.annotations.autoremove/ecal-sample-pubsub: "TRUE"
        io.podman.annotations.cid-file/ecal-sample-pubsub: /run/ecal-sample-pubsub.cid
        io.podman.annotations.init/ecal-sample-pubsub: "TRUE"
        io.podman.annotations.privileged/ecal-sample-pubsub: "FALSE"
        io.podman.annotations.publish-all/ecal-sample-pubsub: "FALSE"
      labels:
        app: ecal-sample-pubsub
      name: ecal-sample-pubsub
    spec:
      shareProcessNamespace: true
      containers:
      - image: localhost/ecal-cpp-subscriber:latest
        name: sub
        command:
          - /opt/app/_build/hello_world_rec
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
        - mountPath: /etc/ecal
          name: ecal
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      - image: localhost/ecal-cpp-publisher:latest
        name: pub
        command:
          - /opt/app/_build/hello_world_snd
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
        - mountPath: /etc/ecal
          name: ecal
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - hostPath:
          path: tmpfs
          type: DirectoryOrCreate
        name: tmpfs
      - hostPath:
          path: /etc/ecal
          type: Directory
        name: ecal
