version: '2'
mpp-vars:
  image_rpms:
    mpp-join:
    - mpp-eval: locals().get('extra_image_rpms', [])
    - []
pipelines:
- name: ostree-tree
  build: name:build
  stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid:
        mpp-eval: rootfs_uuid
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: centos_gpg_key
      - mpp-eval: redhat_gpg_key
      disable_dracut: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          module-platform-id: platform:el9
          baseurl: $cs9_baseurl/BaseOS/$arch/os/
          repos:
            mpp-join:
            - mpp-eval: cs9_repos
            - mpp-eval: cs9_automotive_repos
            - - id: cs9-shim
                baseurl: https://download.copr.fedorainfracloud.org/results/alexl/cs9-shim/fedora-35-$arch/
          packages:
            mpp-join:
            - mpp-eval: base_rpms
            - mpp-eval: boot_rpms
            - - shim-unsigned-$efiarch
          excludes:
          - dracut-config-rescue
  - type: org.osbuild.mkdir
    options:
      paths:
      - path: /boot/efi/EFI/Linux
        parents: true
  - type: org.osbuild.copy
    inputs:
      bootcsv:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: directboot.csv
          path: ../directboot.csv
    options:
      paths:
      - from:
          mpp-format-string: input://bootcsv/{embedded['directboot.csv']}
        to: tree:///boot/efi/EFI/Linux/boot.csv
  - type: org.osbuild.dracut
    options:
      kernel:
      - mpp-eval: rpms['ostree-tree'][kernel_rpm + '-core'].evra
      add_modules:
      - base
      - bash
      - dracut-systemd
      - fs-lib
      - i18n
      - kernel-modules
      - kernel-modules-extra
      - rootfs-block
      - shutdown
      - systemd
      - systemd-initrd
      - terminfo
      - udev-rules
      - usrmount
      omit_modules:
      - dm
      - lunmask
      - mdraid
      - memstrack
      - nss-softokn
      - nvdimm
      - resume
      - terminfo
      add_drivers:
        mpp-join:
        - mpp-eval: locals().get('target_dracut_drivers', [])
        - []
      filesystems:
      - xfs
      - vfat
      - ext4
      install:
      - /.buildstamp
      extra:
      - /boot/efi/EFI/Linux/initramfs.img
      - --kernel-cmdline
      - mpp-format-string: root=UUID={rootfs_uuid} {' ' .join(kernel_opts)}
- name: ostree-commit
  stages:
  - type: org.osbuild.noop
- name: image-tree
  build: name:build
  stages:
  - type: org.osbuild.copy
    inputs:
      tree:
        type: org.osbuild.tree
        origin: org.osbuild.pipeline
        references:
        - name:rootfs
    options:
      paths:
      - from: input://tree/
        to: tree:///
  - type: org.osbuild.copy
    inputs:
      kernel:
        type: org.osbuild.tree
        origin: org.osbuild.pipeline
        references:
        - name:ostree-tree
    options:
      paths:
      - from: input://kernel/lib/modules
        to: tree:///lib/
      - from: input://kernel/boot/efi/EFI/BOOT
        to: tree:////boot/efi/EFI/
      - from: input://kernel/boot/efi/EFI/Linux
        to: tree:////boot/efi/EFI/
  - type: org.osbuild.copy
    inputs:
      kernel:
        type: org.osbuild.tree
        origin: org.osbuild.pipeline
        references:
        - name:ostree-tree
    options:
      paths:
      - from: input://kernel/lib/modules
        to: tree:///lib/
      - from: input://kernel/boot/efi/EFI/BOOT
        to: tree:////boot/efi/EFI/
      - from: input://kernel/boot/efi/EFI/Linux
        to: tree:////boot/efi/EFI/
  - mpp-if: arch == 'aarch64'
    then:
      type: org.osbuild.gunzip
      inputs:
        file:
          type: org.osbuild.files
          origin: org.osbuild.pipeline
          references:
            name:ostree-tree:
              file:
                mpp-format-string: boot/vmlinuz-{rpms['ostree-tree'][kernel_rpm + '-core'].evra}
      options:
        path: /boot/efi/EFI/Linux/linux.efi
    else:
      type: org.osbuild.copy
      inputs:
        kernel:
          type: org.osbuild.tree
          origin: org.osbuild.pipeline
          references:
          - name:ostree-tree
      options:
        paths:
        - from:
            mpp-format-string: input://kernel/boot/vmlinuz-{rpms['ostree-tree'][kernel_rpm + '-core'].evra}
          to: tree:///boot/efi/EFI/Linux/linux.efi
  - type: org.osbuild.fstab
    options:
      filesystems:
      - uuid:
          mpp-eval: rootfs_uuid
        vfs_type: xfs
        path: /
        freq: 1
        passno: 1
      - label: ESP
        vfs_type: vfat
        path: /boot/efi
        freq: 1
        passno: 1
      - uuid:
          mpp-eval: bootfs_uuid
        vfs_type: ext4
        path: /boot
        freq: 1
        passno: 1
  - type: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
