version: '2'
mpp-vars:
  name: neptune
pipelines:
- mpp-import-pipelines:
    path: include/cs9-build.ipp.yml
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid:
        mpp-eval: rootfs_uuid
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: centos_gpg_key
      - mpp-eval: redhat_gpg_key
      disable_dracut: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          module-platform-id: platform:el9
          baseurl: $cs9_baseurl/BaseOS/$arch/os/
          repos:
            mpp-join:
            - mpp-eval: cs9_repos
            - mpp-eval: cs9_automotive_repos
            - mpp-eval: target_repos
            - - id: copr-neptune
                baseurl: https://download.copr.fedorainfracloud.org/results/pingou/qtappmanager-fedora/centos-stream-9-$arch/
          packages:
            mpp-join:
            - mpp-eval: base_rpms
            - mpp-eval: image_rpms
            - mpp-eval: extra_rpms
            - - dnf
              - firewalld
              - gdm
              - gnome-control-center
              - gnome-session-xsession
              - gnome-shell
              - gnome-terminal
              - langpacks-en
              - neptune3-ui
              - openssh-clients
              - openssh-server
              - plymouth
              - polkit
              - sudo
              - xorg-x11-drv-fbdev
          excludes:
          - dracut-config-rescue
          - gnome-tour
  - type: org.osbuild.locale
    options:
      language: en_US.UTF-8
  - type: org.osbuild.users
    options:
      users:
        guest:
          password:
            mpp-eval: guest_password
        neptune:
          password: ''
  - type: org.osbuild.copy
    inputs:
      inlinefile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: custom.conf
          path: ../files/etc/gdm/custom.conf
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile/{embedded['custom.conf']}
        to: tree:///etc/gdm/custom.conf
  - type: org.osbuild.copy
    inputs:
      inlinefile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: neptune-accounts-service-init.service
          path: ../files/etc/systemd/system/neptune-accounts-service-init.service
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile/{embedded['neptune-accounts-service-init.service']}
        to: tree:///etc/systemd/system/neptune-accounts-service-init.service
  - type: org.osbuild.copy
    inputs:
      inlinefile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: neptune-wayland.desktop
          path: ../files/usr/share/wayland-sessions/neptune-wayland.desktop
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile/{embedded['neptune-wayland.desktop']}
        to: tree:///usr/share/wayland-sessions/neptune-wayland.desktop
  - type: org.osbuild.copy
    inputs:
      inlinefile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: neptune.session
          path: ../files/usr/share/gnome-session/sessions/neptune.session
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile/{embedded['neptune.session']}
        to: tree:///usr/share/gnome-session/sessions/neptune.session
  - type: org.osbuild.copy
    inputs:
      inlinefile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: am-config-neptune.yaml
          path: ../files/usr/lib64/neptune3/am-config-neptune.yaml
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile/{embedded['am-config-neptune.yaml']}
        to: tree:///usr/lib64/neptune3/am-config-neptune.yaml
  - type: org.osbuild.copy
    inputs:
      inlinefile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: neptune3-ui.desktop
          path: ../files/usr/share/applications/neptune3-ui.desktop
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile/{embedded['neptune3-ui.desktop']}
        to: tree:///usr/share/applications/neptune3-ui.desktop
  - type: org.osbuild.systemd
    options:
      enabled_services:
      - NetworkManager.service
      - firewalld.service
      - rngd.service
      - sshd.service
      - neptune-accounts-service-init.service
- mpp-import-pipelines:
    path: include/cs9-image.ipp.yml
