version: '2'
mpp-vars:
  name: osbuilder
pipelines:
- mpp-import-pipelines:
    path: include/cs9-build.ipp.yml
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid:
        mpp-eval: rootfs_uuid
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: centos_gpg_key
      - mpp-eval: redhat_gpg_key
      disable_dracut: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          module-platform-id: platform:el9
          baseurl: $cs9_baseurl/BaseOS/$arch/os/
          repos:
            mpp-join:
            - mpp-eval: cs9_repos
            - mpp-eval: cs9_automotive_repos
            - mpp-eval: target_repos
            - - id: osbuild
                baseurl: https://download.copr.fedorainfracloud.org/results/@osbuild/osbuild/centos-stream-9-$arch

          packages:
            mpp-join:
            - mpp-eval: base_rpms
            - mpp-eval: image_rpms
            - mpp-eval: extra_rpms
            - - "@Development Tools"
              - bash-completion
              - dnf
              - emacs
              - git
              - less
              - osbuild-ostree
              - osbuild-tools
              - qemu-kvm
              - strace
              - sudo
              - vim
          excludes:
          - dracut-config-rescue
  - type: org.osbuild.locale
    options:
      language: en_US.UTF-8
  - type: org.osbuild.users
    options:
      users:
        guest:
          password:
            mpp-eval: guest_password
          "groups":
            - wheel
  - type: org.osbuild.systemd
    options:
      enabled_services:
      - NetworkManager.service
      - rngd.service
- mpp-import-pipelines:
    path: include/cs9-image.ipp.yml
