version: '2'
mpp-vars:
  ostree_ref: cs9/$arch/minimal
  image_size: '8589934592'
  rootfs_uuid: 76a22bf4-f153-4541-b6c7-0332c0dfaeac
  bootfs_uuid: 156f0420-627b-4151-ae6f-fda298097515
  extra_rpms: []
  image_type: ostree
  kernel_rpm: kernel-auto
  kernel_opts:
  - ro
  - console=tty0
  - console=ttyS0
  - systemd.log_target=console
  - systemd.journald.forward_to_console=1
pipelines:
- mpp-import-pipelines:
    path: ../cs9-build.mpp.yml
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid:
        mpp-eval: rootfs_uuid
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: centos_gpg_key
      - mpp-eval: redhat_gpg_key
      disable_dracut: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          module-platform-id: platform:el9
          baseurl: $cs9_baseurl/BaseOS/$arch/os/
          repos:
            mpp-join:
            - mpp-eval: cs9_repos
            - mpp-eval: cs9_automotive_repos
            - []
          packages:
            mpp-join:
            - mpp-eval: base_rpms
            - mpp-eval: image_rpms
            - mpp-eval: extra_rpms
            - []
          excludes:
          - dracut-config-rescue
  - type: org.osbuild.locale
    options:
      language: en_US.UTF-8
  - type: org.osbuild.users
    options:
      users:
        root:
          password: $6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU.
        guest:
          password: $6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU.
  - type: org.osbuild.systemd
    options:
      enabled_services:
      - NetworkManager.service
      - rngd.service
- mpp-import-pipelines:
    path: ../cs9-image.mpp.yml
