version: '2'
mpp-vars:
  image_rpms:
    mpp-join:
    - mpp-eval: locals().get('extra_image_rpms', [])
    - mpp-eval: boot_rpms
    - mpp-eval: locals().get('extra_boot_rpms', [])
    - - shim
pipelines:
- name: image-tree
  build: name:build
  stages:
    mpp-join:
    - - type: org.osbuild.copy
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
            - name:rootfs
          extra-tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
            - name:extra-tree-content
        options:
          paths:
            mpp-join:
              - - from: input://tree/
                  to: tree:///
              - mpp-eval: extra_tree_content
      - type: org.osbuild.users
        options:
          users:
            root:
              password:
                mpp-eval: root_password
              key:
                mpp-eval: root_ssh_key
    - mpp-eval: image_extra_stages
    - - type: org.osbuild.dracut
        options:
          kernel:
          - mpp-eval: rpms['rootfs'][kernel_rpm + '-core'].evra
          add_modules:
            mpp-eval: dracut_add_modules
          omit_modules:
            mpp-eval: dracut_omit_modules
          add_drivers:
            mpp-eval: dracut_add_drivers
          filesystems:
            mpp-eval: dracut_filesystems
          install:
            mpp-eval: dracut_install
      - type: org.osbuild.fstab
        options:
          filesystems:
            mpp-eval: fstab
      - mpp-if: use_grub2
        then:
          type: org.osbuild.grub2
          options:
            root_fs_uuid:
              mpp-eval: rootfs_uuid
            boot_fs_uuid:
              mpp-eval: bootfs_uuid
            kernel_opts:
              mpp-eval: ''' '' .join(kernel_opts)'
            uefi:
              vendor:
                mpp-eval: uefi_vendor
              unified: true
            legacy: false
            write_defaults: false
            greenboot: true
      - type: org.osbuild.fix-bls
        options:
          prefix: /
      - type: org.osbuild.selinux
        options:
          file_contexts: etc/selinux/targeted/contexts/files/file_contexts
