version: '2'
mpp-vars:
  simple_containers: []
  qm_simple_containers: []
  simple_import: include/empty.ipp.yml
  simple_repos: []
  simple_rpms: []
  simple_copy: []
  qm_simple_copy: []
  simple_mkdir: []
  qm_simple_mkdir: []
  simple_remove: []
  qm_simple_remove: []
  simple_chmod: {}
  qm_simple_chmod: {}
  simple_chown: {}
  qm_simple_chown: {}
  simple_systemd: {}
  qm_simple_systemd: {}
  simple_sshd_config: {}
  simple_users: {}
  simple_groups: {}
  simple_add_devel_repos: false
  simple_add_debug_repos: false

pipelines:
  - mpp-import-pipelines:
      path: $simple_import

  - mpp-if: not use_qm
    then:
      name: qm_rootfs_base
      build: name:build
      stages:
        - type: org.osbuild.noop

  # In case use_qm is enabled
  - name: qm_rootfs
    build: name:build
    stages:
      - type: org.osbuild.copy
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:qm_rootfs_base
        options:
          paths:
            - from: input://tree/
              to: tree:///
      - mpp-if: qm_simple_containers
        then:
          type: org.osbuild.skopeo
          inputs:
            images:
              type: org.osbuild.containers
              origin: org.osbuild.source
              mpp-resolve-images:
                images:
                  mpp-eval: qm_simple_containers
          options:
            destination:
              type: containers-storage
              storage-path:
                mpp-eval: qm_containers_extra_store
      - mpp-if: qm_simple_mkdir
        then:
          type: org.osbuild.mkdir
          options:
            paths:
              mpp-eval: qm_simple_mkdir
      - mpp-if: qm_simple_remove
        then:
          type: org.osbuild.lorax-script
          options:
            path: auto/remove
            product:
              name:
                mpp-eval: "' '.join(qm_simple_remove)"
      - mpp-if: qm_simple_copy
        then:
          type: org.osbuild.copy
          inputs:
            extra:
              type: org.osbuild.tree
              origin: org.osbuild.pipeline
              references:
                - name:extra-image-content
          options:
            paths:
              mpp-eval: qm_simple_copy
      - mpp-if: qm_simple_chown
        then:
          type: org.osbuild.chown
          options:
            items:
              mpp-eval: qm_simple_chown
      - mpp-if: qm_simple_chmod
        then:
          type: org.osbuild.chmod
          options:
            items:
              mpp-eval: qm_simple_chmod
      - mpp-if: qm_simple_systemd
        then:
          type: org.osbuild.systemd
          options:
            mpp-eval: qm_simple_systemd

  - name: rootfs
    build: name:build
    stages:
      - type: org.osbuild.rpm
        options:
          gpgkeys:
            - mpp-eval: distro_gpg_keys
          disable_dracut: true
          exclude:
            docs: true
        inputs:
          packages:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-depsolve:
              architecture: $arch
              ignore-weak-deps: true
              module-platform-id: $distro_module_id
              baseurl: $distro_baseurl_repo
              repos:
                mpp-join:
                  - mpp-eval: image_repos
                  - mpp-eval: extra_repos
                  - mpp-eval: simple_repos
                  - mpp-if: simple_add_devel_repos
                    then:
                      mpp-eval: image_devel_repos
                  - mpp-if: simple_add_debug_repos
                    then:
                      mpp-eval: image_debug_repos
              packages:
                mpp-join:
                  - mpp-eval: image_rpms
                  - mpp-eval: extra_rpms
                  - mpp-eval: simple_rpms
      - mpp-if: simple_containers
        then:
          type: org.osbuild.skopeo
          inputs:
            images:
              type: org.osbuild.containers
              origin: org.osbuild.source
              mpp-resolve-images:
                images:
                  mpp-eval: simple_containers
          options:
            destination:
              type: containers-storage
              storage-path:
                mpp-eval: containers_extra_store
      - mpp-if: simple_mkdir
        then:
          type: org.osbuild.mkdir
          options:
            paths:
              mpp-eval: simple_mkdir
      - mpp-if: simple_remove
        then:
          type: org.osbuild.lorax-script
          options:
            path: auto/remove
            product:
              name:
                mpp-eval: "' '.join(simple_remove)"
      - mpp-if: simple_copy
        then:
          type: org.osbuild.copy
          inputs:
            extra:
              type: org.osbuild.tree
              origin: org.osbuild.pipeline
              references:
                - name:extra-image-content
          options:
            paths:
              mpp-eval: simple_copy
      - mpp-if: simple_chown
        then:
          type: org.osbuild.chown
          options:
            items:
              mpp-eval: simple_chown
      - mpp-if: simple_chmod
        then:
          type: org.osbuild.chmod
          options:
            items:
              mpp-eval: simple_chmod
      - mpp-if: simple_systemd
        then:
          type: org.osbuild.systemd
          options:
            mpp-eval: simple_systemd
      - mpp-if: simple_sshd_config
        then:
          type: org.osbuild.sshd.config
          options:
            config:
              mpp-eval: simple_sshd_config
      - mpp-if: simple_groups
        then:
          type: org.osbuild.groups
          options:
            groups:
              mpp-eval: simple_groups
      - mpp-if: simple_users
        then:
          type: org.osbuild.users
          options:
            users:
              mpp-eval: simple_users
