apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/etc/cyclonedds: Z
    io.kubernetes.cri-o.TTY/adkit-api: "false"
    io.podman.annotations.autoremove/adkit-api: "TRUE"
    io.podman.annotations.cid-file/adkit-api: /run/adkit-api.cid
    io.podman.annotations.init/adkit-api: "TRUE"
    io.podman.annotations.privileged/adkit-api: "FALSE"
    io.podman.annotations.publish-all/adkit-api: "FALSE"
  labels:
    app: adkit-api
  name: adkit-api
spec:
  hostNetwork: true
  containers:
  - image: localhost/autoware-universe:latest
    name: app
    command:
    - /bin/bash
    - -c
    - "source install/setup.bash; ros2 launch tier4_autoware_api_launch autoware_api.launch.xml init_simulator_pose:=true init_localization_pose:=false"
    env:
    - name: CYCLONEDDS_URI
      value: file:///etc/cyclonedds/cyclonedds.xml
    - name: RMW_IMPLEMENTATION
      value: rmw_cyclonedds_cpp
    securityContext:
      seLinuxOptions:
        type: 'spc_t'
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /etc/cyclonedds
      name: cyclonedds
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
  volumes:
  - hostPath:
      path: tmpfs
      type: DirectoryOrCreate
    name: tmpfs
  - hostPath:
      path: /etc/adkit/cyclonedds
      type: Directory
    name: cyclonedds
