apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/etc/cyclonedds: Z
    bind-mount-options:/map: Z
    io.kubernetes.cri-o.TTY/adkit-simulator: "false"
    io.podman.annotations.autoremove/adkit-simulator: "TRUE"
    io.podman.annotations.cid-file/adkit-simulator: /run/adkit-simulator.cid
    io.podman.annotations.init/adkit-simulator: "TRUE"
    io.podman.annotations.privileged/adkit-simulator: "FALSE"
    io.podman.annotations.publish-all/adkit-simulator: "FALSE"
  labels:
    app: adkit-simulator
  name: adkit-simulator
spec:
  hostNetwork: true
  containers:
  - image: localhost/scenario_simulator:latest
    name: app
    command: ["sleep", "infinity"]
    env:
    - name: CYCLONEDDS_URI
      value: file:///etc/cyclonedds/cyclonedds.xml
    - name: RMW_IMPLEMENTATION
      value: rmw_cyclonedds_cpp
    securityContext:
      seLinuxOptions:
        type: 'spc_t'
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /etc/cyclonedds
      name: cyclonedds
    - name: map
      mountPath: /map
    - name: conf
      mountPath: /sample_data
    - name: bin
      mountPath: /opt/adkit/simulator/bin
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
  volumes:
    - name: tmpfs
      hostPath:
        path: tmpfs
        type: DirectoryOrCreate
    - name: cyclonedds
      hostPath:
        path: /etc/adkit/cyclonedds
        # path: /etc/adkit/simulator/cyclonedds
        type: Directory
    - name: map
      hostPath:
        path: /etc/adkit/map
        type: Directory
    - name: conf
      hostPath:
        path: /etc/adkit/simulator/conf
        type: Directory
    - name: bin
      hostPath:
        path: /etc/adkit/simulator/bin
        type: Directory
