apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/etc/cyclonedds: Z
    bind-mount-options:/map: Z
    io.kubernetes.cri-o.TTY/adkit-control: "false"
    io.podman.annotations.autoremove/adkit-control: "TRUE"
    io.podman.annotations.cid-file/adkit-control: /run/adkit-control.cid
    io.podman.annotations.init/adkit-control: "TRUE"
    io.podman.annotations.privileged/adkit-control: "FALSE"
    io.podman.annotations.publish-all/adkit-contrl: "FALSE"
  labels:
    app: adkit-control
  name: adkit-control
spec:
  hostNetwork: true
  containers:
  - image: localhost/autoware-universe:latest
    name: app
    command:
    - /bin/bash
    - -c
    - "source install/setup.bash;  ros2 launch tier4_control_launch control.launch.py lateral_controller_mode:=mpc_follower vehicle_info_param_file:=$(ros2 pkg prefix sample_vehicle_description)/share/sample_vehicle_description/config/vehicle_info.param.yaml"
    env:
    - name: CYCLONEDDS_URI
      value: file:///etc/cyclonedds/cyclonedds.xml
    - name: RMW_IMPLEMENTATION
      value: rmw_cyclonedds_cpp
    securityContext:
      seLinuxOptions:
        type: 'spc_t'
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /etc/cyclonedds
      name: cyclonedds
    - name: map
      mountPath: /map
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
  volumes:
    - name: tmpfs
      hostPath:
        path: tmpfs
        type: DirectoryOrCreate
    - name: cyclonedds
      hostPath:
        path: /etc/adkit/cyclonedds
        type: Directory
    - name: map
      hostPath:
        path: /etc/adkit/map
        type: Directory
