# This is a wrapper manifest for any bootc bootable container
# Just build this, overriding the oci_* variables below to point to your real image
# For example:
#  make cs9-qemu-ocibased-ostree.x86_64.qcow2 DEFINES='oci_source="quay.io/my/thing" oci_source_tag="latest"'

version: '2'
mpp-vars:
  name: ocibased
  use_ocibased: True
  oci_source: quay.io/automotive-toolchain/autosd
  oci_source_tag: minimal
  extra_build_repos:
    # For now we need a newer rpm-ostree (2023.10) for the container support;
    - id: composefs-test
      baseurl: https://download.copr.fedorainfracloud.org/results/alexl/composefs-test/centos-stream+epel-next-9-$arch
pipelines:
- mpp-import-pipelines:
    path: include/build.ipp.yml

# This is not actually used, as the rootfs comes from the image,
# However, it is referenced by some other stuff atm so we have to have
# *something* with this name
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.noop

- mpp-import-pipelines:
    path: include/image.ipp.yml
