version: '2'
mpp-vars:
  name: soafee
  use_containers: true
pipelines:
- mpp-import-pipelines:
    path: include/build.ipp.yml
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid:
        mpp-eval: rootfs_uuid
      kernel_opts:
        mpp-eval: ''' '' .join(kernel_opts)'
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: centos_gpg_key
      - mpp-eval: redhat_gpg_key
      disable_dracut: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          ignore-weak-deps: true
          module-platform-id: $distro_module_id
          baseurl: $distro_baseurl/BaseOS/$arch/os/
          repos:
            mpp-join:
            - mpp-eval: image_repos
            - mpp-eval: extra_repos
          packages:
            mpp-join:
            - mpp-eval: image_rpms
            - mpp-eval: extra_rpms
            - - podman
              - containernetworking-plugins
              - curl
          excludes:
          - dracut-config-rescue
  - type: org.osbuild.skopeo
    inputs:
      images:
        type: org.osbuild.containers
        origin: org.osbuild.source
        mpp-resolve-images:
          images:
            - source: docker.io/library/httpd
              tag: latest
              name: localhost/httpd
    options:
      destination:
        type: containers-storage
        storage-path: /usr/share/containers/storage
  - type: org.osbuild.mkdir
    options:
      paths:
      - path: /etc/httpd/htdocs
        parents: true
  - type: org.osbuild.copy
    inputs:
      docfile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: index.html
          url: https://ygalblum.github.io/soafee-on-autosd-doc/index.html
      podspec:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: podfile
          path: ../files/httpd-doc.yml
      unitfile:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: unitfile
          path: ../files/httpd-doc.service
    options:
      paths:
      - from:
          mpp-format-string: input://docfile/{embedded['index.html']}
        to: tree:///etc/httpd/htdocs/index.html
      - from:
          mpp-format-string: input://podspec/{embedded['podfile']}
        to: tree:///etc/httpd/httpd-doc.yml
      - from:
          mpp-format-string: input://unitfile/{embedded['unitfile']}
        to: tree:///usr/lib/systemd/system/httpd-doc.service
  - type: org.osbuild.systemd
    options:
      enabled_services:
      - httpd-doc.service
- mpp-import-pipelines:
    path: include/image.ipp.yml
