# This is a qemu target similar to the regular "qemu" target, but using
# an android boot partition instead of grub.
#
# It is rather slow as it doesn't use KVM, if you want that use the
# abootqemukvm target instead
#
# It currently works only on aarch64, and you need to use a u-boot
# firmware that supports aboot to boot it, which can be
# done by passing --aboot to runvm.
#
version: '2'
# To derive and override mpp vars we move the overrides to an include file
pipelines:
  - mpp-import-pipelines:
      path: qemu.ipp.yml
  - mpp-import-pipelines:
      path: _abootqemu.ipp.yml
